export type LabelMap = {
  [key: string]: string;
};

// Default mappings - add your custom mappings here
export const defaultLabelMap: LabelMap = {
  'person': 'ひと',
  'bicycle': 'じてんしゃ',
  'car': 'くるま',
  'motorcycle': 'オートバイ',
  'airplane': 'ひこうき',
  'bus': 'バス',
  'train': 'でんしゃ',
  'truck': 'トラック',
  'boat': 'ボート',
  'traffic light': 'しんごう',
  'fire hydrant': '消火栓',
  'stop sign': '一時停止標識',
  'parking meter': 'パーキングメーター',
  'bench': 'ベンチ',
  'bird': 'とり',
  'cat': 'ねこ',
  'dog': 'いぬ',
  'horse': 'うま',
  'sheep': 'ひつじ',
  'cow': 'うし',
  'elephant': 'ぞう',
  'bear': 'くま',
  'zebra': 'しまうま',
  'giraffe': 'きりん',
  'backpack': 'リュックサック',
  'umbrella': 'かさ',
  'handbag': 'ハンドバッグ',
  'tie': 'ネクタイ',
  'suitcase': 'スーツケース',
  'frisbee': 'フリスビー',
  'skis': 'スキー',
  'snowboard': 'スノーボード',
  'sports ball': 'スポーツボール',
  'kite': 'たこ',
  'baseball bat': '野球バット',
  'baseball glove': '野球グローブ',
  'skateboard': 'スケートボード',
  'surfboard': 'サーフボード',
  'tennis racket': 'テニスラケット',
  'bottle': 'ボトル',
  'wine glass': 'ワイングラス',
  'cup': 'カップ',
  'fork': 'フォーク',
  'knife': 'ナイフ',
  'spoon': 'スプーン',
  'bowl': 'ボウル',
  'banana': 'バナナ',
  'apple': 'りんご',
  'sandwich': 'サンドイッチ',
  'orange': 'オレンジ',
  'broccoli': 'ブロッコリー',
  'carrot': 'にんじん',
  'hot dog': 'ホットドッグ',
  'pizza': 'ピザ',
  'donut': 'ドーナツ',
  'cake': 'ケーキ',
  'chair': 'いす',
  'couch': 'ソファー',
  'potted plant': '鉢植え',
  'bed': 'ベッド',
  'dining table': 'ダイニングテーブル',
  'toilet': 'トイレ',
  'tv': 'テレビ',
  'laptop': 'ノートパソコン',
  'mouse': 'マウス',
  'remote': 'リモコン',
  'keyboard': 'キーボード',
  'cell phone': '携帯電話',
  'microwave': '電子レンジ',
  'oven': 'オーブン',
  'toaster': 'トースター',
  'sink': '流し',
  'refrigerator': '冷蔵庫',
  'book': '本',
  'clock': '時計',
  'vase': '花瓶',
  'scissors': 'はさみ',
  'teddy bear': 'テディベア',
  'hair drier': 'ヘアドライヤー',
  'toothbrush': '歯ブラシ'
};

export const mapLabel = (originalLabel: string, customMap: LabelMap = defaultLabelMap): string => {
  return customMap[originalLabel] || originalLabel;
};