import { QuizQuestion } from '../components/quiz/types';

interface QuizData {
  type: 'hiragana' | 'katakana';
  japanese: string;
  romaji: string;
}

const hiraganaData: QuizData[] = [
  // Basic Kana (Gojūon)
  { type: 'hiragana', japanese: 'あ', romaji: 'a' },
  { type: 'hiragana', japanese: 'い', romaji: 'i' },
  { type: 'hiragana', japanese: 'う', romaji: 'u' },
  { type: 'hiragana', japanese: 'え', romaji: 'e' },
  { type: 'hiragana', japanese: 'お', romaji: 'o' },
  { type: 'hiragana', japanese: 'か', romaji: 'ka' },
  { type: 'hiragana', japanese: 'き', romaji: 'ki' },
  { type: 'hiragana', japanese: 'く', romaji: 'ku' },
  { type: 'hiragana', japanese: 'け', romaji: 'ke' },
  { type: 'hiragana', japanese: 'こ', romaji: 'ko' },
  { type: 'hiragana', japanese: 'さ', romaji: 'sa' },
  { type: 'hiragana', japanese: 'し', romaji: 'shi' },
  { type: 'hiragana', japanese: 'す', romaji: 'su' },
  { type: 'hiragana', japanese: 'せ', romaji: 'se' },
  { type: 'hiragana', japanese: 'そ', romaji: 'so' },
  { type: 'hiragana', japanese: 'た', romaji: 'ta' },
  { type: 'hiragana', japanese: 'ち', romaji: 'chi' },
  { type: 'hiragana', japanese: 'つ', romaji: 'tsu' },
  { type: 'hiragana', japanese: 'て', romaji: 'te' },
  { type: 'hiragana', japanese: 'と', romaji: 'to' },
  { type: 'hiragana', japanese: 'な', romaji: 'na' },
  { type: 'hiragana', japanese: 'に', romaji: 'ni' },
  { type: 'hiragana', japanese: 'ぬ', romaji: 'nu' },
  { type: 'hiragana', japanese: 'ね', romaji: 'ne' },
  { type: 'hiragana', japanese: 'の', romaji: 'no' },
  { type: 'hiragana', japanese: 'は', romaji: 'ha' },
  { type: 'hiragana', japanese: 'ひ', romaji: 'hi' },
  { type: 'hiragana', japanese: 'ふ', romaji: 'fu' },
  { type: 'hiragana', japanese: 'へ', romaji: 'he' },
  { type: 'hiragana', japanese: 'ほ', romaji: 'ho' },
  { type: 'hiragana', japanese: 'ま', romaji: 'ma' },
  { type: 'hiragana', japanese: 'み', romaji: 'mi' },
  { type: 'hiragana', japanese: 'む', romaji: 'mu' },
  { type: 'hiragana', japanese: 'め', romaji: 'me' },
  { type: 'hiragana', japanese: 'も', romaji: 'mo' },
  { type: 'hiragana', japanese: 'や', romaji: 'ya' },
  { type: 'hiragana', japanese: 'ゆ', romaji: 'yu' },
  { type: 'hiragana', japanese: 'よ', romaji: 'yo' },
  { type: 'hiragana', japanese: 'ら', romaji: 'ra' },
  { type: 'hiragana', japanese: 'り', romaji: 'ri' },
  { type: 'hiragana', japanese: 'る', romaji: 'ru' },
  { type: 'hiragana', japanese: 'れ', romaji: 're' },
  { type: 'hiragana', japanese: 'ろ', romaji: 'ro' },
  { type: 'hiragana', japanese: 'わ', romaji: 'wa' },
  { type: 'hiragana', japanese: 'を', romaji: 'wo' },
  { type: 'hiragana', japanese: 'ん', romaji: 'n' },

  // Dakuten (voiced sounds)
  { type: 'hiragana', japanese: 'が', romaji: 'ga' },
  { type: 'hiragana', japanese: 'ぎ', romaji: 'gi' },
  { type: 'hiragana', japanese: 'ぐ', romaji: 'gu' },
  { type: 'hiragana', japanese: 'げ', romaji: 'ge' },
  { type: 'hiragana', japanese: 'ご', romaji: 'go' },
  { type: 'hiragana', japanese: 'ざ', romaji: 'za' },
  { type: 'hiragana', japanese: 'じ', romaji: 'ji' },
  { type: 'hiragana', japanese: 'ず', romaji: 'zu' },
  { type: 'hiragana', japanese: 'ぜ', romaji: 'ze' },
  { type: 'hiragana', japanese: 'ぞ', romaji: 'zo' },
  { type: 'hiragana', japanese: 'だ', romaji: 'da' },
  { type: 'hiragana', japanese: 'ぢ', romaji: 'ji' },
  { type: 'hiragana', japanese: 'づ', romaji: 'zu' },
  { type: 'hiragana', japanese: 'で', romaji: 'de' },
  { type: 'hiragana', japanese: 'ど', romaji: 'do' },
  { type: 'hiragana', japanese: 'ば', romaji: 'ba' },
  { type: 'hiragana', japanese: 'び', romaji: 'bi' },
  { type: 'hiragana', japanese: 'ぶ', romaji: 'bu' },
  { type: 'hiragana', japanese: 'べ', romaji: 'be' },
  { type: 'hiragana', japanese: 'ぼ', romaji: 'bo' },

  // Handakuten (semi-voiced sounds)
  { type: 'hiragana', japanese: 'ぱ', romaji: 'pa' },
  { type: 'hiragana', japanese: 'ぴ', romaji: 'pi' },
  { type: 'hiragana', japanese: 'ぷ', romaji: 'pu' },
  { type: 'hiragana', japanese: 'ぺ', romaji: 'pe' },
  { type: 'hiragana', japanese: 'ぽ', romaji: 'po' },

  // Yōon (combination sounds)
  { type: 'hiragana', japanese: 'きゃ', romaji: 'kya' },
  { type: 'hiragana', japanese: 'きゅ', romaji: 'kyu' },
  { type: 'hiragana', japanese: 'きょ', romaji: 'kyo' },
  { type: 'hiragana', japanese: 'しゃ', romaji: 'sha' },
  { type: 'hiragana', japanese: 'しゅ', romaji: 'shu' },
  { type: 'hiragana', japanese: 'しょ', romaji: 'sho' },
  { type: 'hiragana', japanese: 'ちゃ', romaji: 'cha' },
  { type: 'hiragana', japanese: 'ちゅ', romaji: 'chu' },
  { type: 'hiragana', japanese: 'ちょ', romaji: 'cho' },
  { type: 'hiragana', japanese: 'にゃ', romaji: 'nya' },
  { type: 'hiragana', japanese: 'にゅ', romaji: 'nyu' },
  { type: 'hiragana', japanese: 'にょ', romaji: 'nyo' },
  { type: 'hiragana', japanese: 'ひゃ', romaji: 'hya' },
  { type: 'hiragana', japanese: 'ひゅ', romaji: 'hyu' },
  { type: 'hiragana', japanese: 'ひょ', romaji: 'hyo' },
  { type: 'hiragana', japanese: 'みゃ', romaji: 'mya' },
  { type: 'hiragana', japanese: 'みゅ', romaji: 'myu' },
  { type: 'hiragana', japanese: 'みょ', romaji: 'myo' },
  { type: 'hiragana', japanese: 'りゃ', romaji: 'rya' },
  { type: 'hiragana', japanese: 'りゅ', romaji: 'ryu' },
  { type: 'hiragana', japanese: 'りょ', romaji: 'ryo' },
  { type: 'hiragana', japanese: 'ぎゃ', romaji: 'gya' },
  { type: 'hiragana', japanese: 'ぎゅ', romaji: 'gyu' },
  { type: 'hiragana', japanese: 'ぎょ', romaji: 'gyo' },
  { type: 'hiragana', japanese: 'じゃ', romaji: 'ja' },
  { type: 'hiragana', japanese: 'じゅ', romaji: 'ju' },
  { type: 'hiragana', japanese: 'じょ', romaji: 'jo' },
  { type: 'hiragana', japanese: 'ぢゃ', romaji: 'ja' },
  { type: 'hiragana', japanese: 'ぢゅ', romaji: 'ju' },
  { type: 'hiragana', japanese: 'ぢょ', romaji: 'jo' },
  { type: 'hiragana', japanese: 'びゃ', romaji: 'bya' },
  { type: 'hiragana', japanese: 'びゅ', romaji: 'byu' },
  { type: 'hiragana', japanese: 'びょ', romaji: 'byo' },
  { type: 'hiragana', japanese: 'ぴゃ', romaji: 'pya' },
  { type: 'hiragana', japanese: 'ぴゅ', romaji: 'pyu' },
  { type: 'hiragana', japanese: 'ぴょ', romaji: 'pyo' },
];

const katakanaData: QuizData[] = [
  // Basic Kana (Gojūon)
  { type: 'katakana', japanese: 'ア', romaji: 'a' },
  { type: 'katakana', japanese: 'イ', romaji: 'i' },
  { type: 'katakana', japanese: 'ウ', romaji: 'u' },
  { type: 'katakana', japanese: 'エ', romaji: 'e' },
  { type: 'katakana', japanese: 'オ', romaji: 'o' },
  { type: 'katakana', japanese: 'カ', romaji: 'ka' },
  { type: 'katakana', japanese: 'キ', romaji: 'ki' },
  { type: 'katakana', japanese: 'ク', romaji: 'ku' },
  { type: 'katakana', japanese: 'ケ', romaji: 'ke' },
  { type: 'katakana', japanese: 'コ', romaji: 'ko' },
  { type: 'katakana', japanese: 'サ', romaji: 'sa' },
  { type: 'katakana', japanese: 'シ', romaji: 'shi' },
  { type: 'katakana', japanese: 'ス', romaji: 'su' },
  { type: 'katakana', japanese: 'セ', romaji: 'se' },
  { type: 'katakana', japanese: 'ソ', romaji: 'so' },
  { type: 'katakana', japanese: 'タ', romaji: 'ta' },
  { type: 'katakana', japanese: 'チ', romaji: 'chi' },
  { type: 'katakana', japanese: 'ツ', romaji: 'tsu' },
  { type: 'katakana', japanese: 'テ', romaji: 'te' },
  { type: 'katakana', japanese: 'ト', romaji: 'to' },
  { type: 'katakana', japanese: 'ナ', romaji: 'na' },
  { type: 'katakana', japanese: 'ニ', romaji: 'ni' },
  { type: 'katakana', japanese: 'ヌ', romaji: 'nu' },
  { type: 'katakana', japanese: 'ネ', romaji: 'ne' },
  { type: 'katakana', japanese: 'ノ', romaji: 'no' },
  { type: 'katakana', japanese: 'ハ', romaji: 'ha' },
  { type: 'katakana', japanese: 'ヒ', romaji: 'hi' },
  { type: 'katakana', japanese: 'フ', romaji: 'fu' },
  { type: 'katakana', japanese: 'ヘ', romaji: 'he' },
  { type: 'katakana', japanese: 'ホ', romaji: 'ho' },
  { type: 'katakana', japanese: 'マ', romaji: 'ma' },
  { type: 'katakana', japanese: 'ミ', romaji: 'mi' },
  { type: 'katakana', japanese: 'ム', romaji: 'mu' },
  { type: 'katakana', japanese: 'メ', romaji: 'me' },
  { type: 'katakana', japanese: 'モ', romaji: 'mo' },
  { type: 'katakana', japanese: 'ヤ', romaji: 'ya' },
  { type: 'katakana', japanese: 'ユ', romaji: 'yu' },
  { type: 'katakana', japanese: 'ヨ', romaji: 'yo' },
  { type: 'katakana', japanese: 'ラ', romaji: 'ra' },
  { type: 'katakana', japanese: 'リ', romaji: 'ri' },
  { type: 'katakana', japanese: 'ル', romaji: 'ru' },
  { type: 'katakana', japanese: 'レ', romaji: 're' },
  { type: 'katakana', japanese: 'ロ', romaji: 'ro' },
  { type: 'katakana', japanese: 'ワ', romaji: 'wa' },
  { type: 'katakana', japanese: 'ヲ', romaji: 'wo' },
  { type: 'katakana', japanese: 'ン', romaji: 'n' },

  // Dakuten (voiced sounds)
  { type: 'katakana', japanese: 'ガ', romaji: 'ga' },
  { type: 'katakana', japanese: 'ギ', romaji: 'gi' },
  { type: 'katakana', japanese: 'グ', romaji: 'gu' },
  { type: 'katakana', japanese: 'ゲ', romaji: 'ge' },
  { type: 'katakana', japanese: 'ゴ', romaji: 'go' },
  { type: 'katakana', japanese: 'ザ', romaji: 'za' },
  { type: 'katakana', japanese: 'ジ', romaji: 'ji' },
  { type: 'katakana', japanese: 'ズ', romaji: 'zu' },
  { type: 'katakana', japanese: 'ゼ', romaji: 'ze' },
  { type: 'katakana', japanese: 'ゾ', romaji: 'zo' },
  { type: 'katakana', japanese: 'ダ', romaji: 'da' },
  { type: 'katakana', japanese: 'ヂ', romaji: 'ji' },
  { type: 'katakana', japanese: 'ヅ', romaji: 'zu' },
  { type: 'katakana', japanese: 'デ', romaji: 'de' },
  { type: 'katakana', japanese: 'ド', romaji: 'do' },
  { type: 'katakana', japanese: 'バ', romaji: 'ba' },
  { type: 'katakana', japanese: 'ビ', romaji: 'bi' },
  { type: 'katakana', japanese: 'ブ', romaji: 'bu' },
  { type: 'katakana', japanese: 'ベ', romaji: 'be' },
  { type: 'katakana', japanese: 'ボ', romaji: 'bo' },

  // Handakuten (semi-voiced sounds)
  { type: 'katakana', japanese: 'パ', romaji: 'pa' },
  { type: 'katakana', japanese: 'ピ', romaji: 'pi' },
  { type: 'katakana', japanese: 'プ', romaji: 'pu' },
  { type: 'katakana', japanese: 'ペ', romaji: 'pe' },
  { type: 'katakana', japanese: 'ポ', romaji: 'po' },
  
  // Yōon (combination sounds)
  { type: 'katakana', japanese: 'キャ', romaji: 'kya' },
  { type: 'katakana', japanese: 'キュ', romaji: 'kyu' },
  { type: 'katakana', japanese: 'キョ', romaji: 'kyo' },
  { type: 'katakana', japanese: 'シャ', romaji: 'sha' },
  { type: 'katakana', japanese: 'シュ', romaji: 'shu' },
  { type: 'katakana', japanese: 'ショ', romaji: 'sho' },
  { type: 'katakana', japanese: 'チャ', romaji: 'cha' },
  { type: 'katakana', japanese: 'チュ', romaji: 'chu' },
  { type: 'katakana', japanese: 'チョ', romaji: 'cho' },
  { type: 'katakana', japanese: 'ニャ', romaji: 'nya' },
  { type: 'katakana', japanese: 'ニュ', romaji: 'nyu' },
  { type: 'katakana', japanese: 'ニョ', romaji: 'nyo' },
  { type: 'katakana', japanese: 'ヒャ', romaji: 'hya' },
  { type: 'katakana', japanese: 'ヒュ', romaji: 'hyu' },
  { type: 'katakana', japanese: 'ヒョ', romaji: 'hyo' },
  { type: 'katakana', japanese: 'ミャ', romaji: 'mya' },
  { type: 'katakana', japanese: 'ミュ', romaji: 'myu' },
  { type: 'katakana', japanese: 'ミョ', romaji: 'myo' },
  { type: 'katakana', japanese: 'リャ', romaji: 'rya' },
  { type: 'katakana', japanese: 'リュ', romaji: 'ryu' },
  { type: 'katakana', japanese: 'リョ', romaji: 'ryo' },
  { type: 'katakana', japanese: 'ギャ', romaji: 'gya' },
  { type: 'katakana', japanese: 'ギュ', romaji: 'gyu' },
  { type: 'katakana', japanese: 'ギョ', romaji: 'gyo' },
  { type: 'katakana', japanese: 'ジャ', romaji: 'ja' },
  { type: 'katakana', japanese: 'ジュ', romaji: 'ju' },
  { type: 'katakana', japanese: 'ジョ', romaji: 'jo' },
  { type: 'katakana', japanese: 'ヂャ', romaji: 'ja' },
  { type: 'katakana', japanese: 'ヂュ', romaji: 'ju' },
  { type: 'katakana', japanese: 'ヂョ', romaji: 'jo' },
  { type: 'katakana', japanese: 'ビャ', romaji: 'bya' },
  { type: 'katakana', japanese: 'ビュ', romaji: 'byu' },
  { type: 'katakana', japanese: 'ビョ', romaji: 'byo' },
  { type: 'katakana', japanese: 'ピャ', romaji: 'pya' },
  { type: 'katakana', japanese: 'ピュ', romaji: 'pyu' },
  { type: 'katakana', japanese: 'ピョ', romaji: 'pyo' },
];

// Fungsi untuk membuat pertanyaan kuis dari data
const createQuizQuestions = (data: QuizData[]): QuizQuestion[] => {
  return data.map(item => {
    // Dapatkan 3 romaji acak lainnya untuk opsi
    const otherItems = data.filter(i => i.romaji !== item.romaji);
    const shuffledOthers = otherItems.sort(() => 0.5 - Math.random()).slice(0, 3);
    const options = [...shuffledOthers.map(i => i.romaji), item.romaji]
      .sort(() => 0.5 - Math.random());

    return {
      question: `${item.japanese} - bagaimana cara membacanya?`,
      options,
      correctAnswer: item.romaji
    };
  });
};

// Buat pertanyaan kuis dari data
export const hiraganaQuestions: QuizQuestion[] = createQuizQuestions(hiraganaData);
export const katakanaQuestions: QuizQuestion[] = createQuizQuestions(katakanaData); 